# Generated by Django 4.0.5 on 2022-07-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recname', models.CharField(max_length=100)),
                ('Recno', models.CharField(max_length=70, unique=True)),
                ('Amt', models.PositiveIntegerField()),
                ('Curr', models.CharField(max_length=10)),
            ],
        ),
    ]
